### ISSUE TITLE
Suggestion: Flex list

### ISSUE THREAD

**Issue by Turtlepaw** [codingki/react-native-rapi-ui#5]
It would be cool to have a flex list component so then developers wouldn't have to worry about flex list CSS.

I was thinking something like this but maybe could be customizable

![msedge_GBRdTmwB0X](https://user-images.githubusercontent.com/81275769/167754811-1f189026-1ab8-4d49-bc27-a9bf04546b9b.png)

**Comment by codingki** [comment]
Thanks for the suggestions, Right now we currently focusing on Rapi UI version 1 which it will be more stable and more components! I will add this to the back log
